### ISSUE TITLE
希望加个好友

### ISSUE THREAD

**Issue by DeadAndLife** [MoLice/TestSpec#1]
你好，关于QMUI-iOS中的#1122的bug，希望能加个好友互相讨论一下，我也挺关心这个问题的。感觉就是runtime等方法中将系统的某个运行逻辑给丢失了一样。我的邮箱iOSzhang@qq.com

**Comment by MoLice** [comment]
QMUI 有微信群，可以加一下
<img src="https://user-images.githubusercontent.com/1190261/101497189-ab39a180-39a5-11eb-91ad-b7f09713faa8.png" width="380" />
